Select ModelID, ModelName, Description, Image, MakeID from viconnect.model
USE viconnect;

CREATE TABLE `model` (
  `ModelID` int(11) NOT NULL AUTO_INCREMENT,
  `ModelName` varchar(40) NOT NULL,
  `Description` text,
  `Image` blob,
  `MakeID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ModelID`)
) ENGINE=InnoDB AUTO_INCREMENT=244 DEFAULT CHARSET=latin1;


insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (1,'DB9','Drivers foot well. Can not be seen without removing carpets and underlay. O/S Chassis under wheel arch,',null,1);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (2,'Alfa Sud','Front of forward bulkhead.',null,2);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (3,'145/146/156','O/S valance or in boot.',null,2);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (4,'166','Floor at drivers seat.',nullnullSystem.Byte[],2);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (5,'A2','Under centre console inside car behind hand brake lever.',null,3);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (6,'A3','Horizontal at wiper panel.',nullnullSystem.Byte[],3);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (7,'A4/A6/A8','Vertical on bulkhead.',nullnullSystem.Byte[],3);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (8,'T T Quottro','Wiper Panel.',null,3);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (9,'A8 (2010 Onwards)','Behind drivers seat. (Slide seat forward and remove air vent and lift flap in carpet.)',null,3);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (10,'Q7','Boot Floor in front of tools.',null,3);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (11,'Q5 ''07','O/S bonnet hindge.',null,3);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (12,'2012 Q7','In Boot (Lift tray).',null,3);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (13,'A3 convertible ''12','O/S inner wing',null,3);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (14,'Bentley','O/S Bonnet Hinge.',null,4);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (15,'3 series 1990 model','Behind driprail at wiper panel.',null,5);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (16,'3 series 00 model','Vertical on bulkhead.',null,5);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (17,'5&7 series','On strut mounting.',null,5);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (18,'Mini','Suspension mount area.',null,5);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (19,'3 series 2012','O/S front inside wing.',null,5);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (20,'X1 2010','O/S front inside wing.',null,5);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (21,'Saxo/Xsara','Inside boot or O/S valance.',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (22,'Xantial/XM/C5','O/S valance.',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (23,'Picasso','Vertical on bulkhead.',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (24,'Relay','Floor at drivers seat.',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (25,'2CV','Bulkhead.',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (26,'C3 Picasso','OS Pillar inside front door.',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (27,'C3','Over washer bottle.',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (28,'C4','Top of valance under plastic ono/s. Shock mounting.',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (29,'C4 ''12 on','Top of osf shock mount (Hard to see) OR as in C3',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (30,'C5','N/S Valance',nullnullSystem.Byte[],6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (31,'C8','Under O/S wiper arm slot in Windscreen.',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (32,'C1','Floor at drivers seat.',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (33,'2012 Berlingo','Top of strut behind wiring loom',null,6);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (34,'Voyager','O/S Shock mounting facing forward',nullnullSystem.Byte[],7);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (35,'Ypsilon','O/S boot floor (Same as Fiat Panda)',null,7);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (36,'05 Jeep','Under plastic trim on o/s door cill.',null,8);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (37,'Jeep','Under carpet in booton O/S beside spear wheel. 07 Under Drivers Seat.',null,8);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (38,'Compass ''10','Passenger side stamped under windscreen',null,8);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (39,'Rexton','Behind n/s fornt wheel under rubber flap.',null,9);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (40,'Matiz','01 Model Drip Rail On Bulkhead',null,10);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (41,'Lanos/Leganza','Vertical on bulkhead.',null,10);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (42,'Nubira','Vertical on bulkhead.',null,10);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (43,'Tacuma','O/S Bulk Head.',null,10);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (44,'Korando/Musso','Under O/S wheel arch behind front wheel',null,10);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (45,'Caliber','Under Driver Seat.',null,11);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (46,'Terios','N/S bulkhead. Over brake servo.',null,12);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (47,'Sirion','08 Bulkhead (under o/s wiper spindle',null,12);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (48,'DeLorean','God knows.',null,13);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (49,'Siecento','O/S/R boot floor.',null,14);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (50,'Panda','O/S Boot floor.',null,14);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (51,'Punto/Multipla','Floor at drivers seat.',null,14);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (52,'Barrachetta/Ducato','Floor at drivers seat.',null,14);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (53,'Ulysesse','Fron of O/S front valance.',null,14);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (54,'Panda/Brava/Bravo','O/S valance.',null,14);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (55,'500 ''08','N/S Boot Floor.',null,14);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (56,'Scudo','O/S valance 08 model. Wiper pannel under flap.',null,14);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (57,'Stilo','Floor at drivers seat.',null,14);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (58,'Uno','O/S suspension mounting.',null,14);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (59,'2012 Panda','Boot floor.',null,14);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (60,'Ka 09','O/S Boot floor.',null,15);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (61,'Fiesta/Ka/Focus','Floor at drivers seat.',nullnullSystem.Byte[],15);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (62,'Transit 05 Type','in front of o/s front wheel.',null,15);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (63,'Mondeo','07 Beside O/S Front seat.',null,15);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (64,'Mondeo','Vertical on valance.',null,15);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (65,'Galaxy','Midway on bulkhead.',null,15);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (66,'Galaxy 07','On the floor along drivers seat.',null,15);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (67,'C Max','Beside drivers seat.',null,15);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (68,'Trerracan','O/S Rear chassas behind wheel.',null,16);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (69,'Tuscon','Brace under drivers seat.',null,16);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (70,'Matrix','Inside o/s valance.',null,16);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (71,'Trajet','O/S inner valance.',null,16);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (72,'Getz','Under D/Seat 04 model.',null,16);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (73,'IX20','Under drivers seat.',null,16);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (74,'i10','Under drivers seat.',null,16);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (75,'i20','Under drivers seat.',null,16);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (76,'i30','Under drivers seat.',null,16);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (77,'i40','Under drivers seat.',null,16);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (78,'Ferrari','Boot Floor. Bonnet pull o/s door pillarr. OS Engine compartment.',null,17);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (79,'All models','Bulkhead.',null,18);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (80,'12 Civic','Remove big plastic panel under wiper.',null,18);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (81,'Jeep 06','Commander under door still plastic',null,19);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (82,'Jeep 03','O/S boot floor',null,20);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (83,'Trouper','O/S/R wheel arch in front of wheel',null,21);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (84,'Some models','Bonnet hinge, in boot or at windscreen. In boot beside battery',null,22);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (85,'XJ 6 ''05','O/S rear shock mounting in the boot.',null,22);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (86,'X Type','In the boot underthe carpet on the o/s',null,22);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (87,'S Type','Behind carpet on o/s rear wheel arch.',null,22);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (88,'XF ''08','Behind rear seat on the O/S bulk head (Pull back carpet next to seat anchor)',null,22);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (89,'XJ','Directly above battery in boot.',null,22);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (90,'Carens','On brace under drivers seat.',null,23);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (91,'Rio','Vertical on bulkhead.',null,23);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (92,'Sportage','O/S/R wheel arch / o/s door',null,23);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (93,'Sportage ''06','Under driver seat.',null,23);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (94,'Sorento','Front pannell o/s top.',null,23);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (95,'Ceed ''09','Under drivers seat.',null,23);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (96,'Picanto 2012','O/S Boot floor.',null,23);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (97,'Sedona','Over Brake master Cylinder.',null,23);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (98,'Rio 2012','Under drivers seat.',null,23);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (99,'Discovery','O/S/F wheel arch in front of wheel.',null,24);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (100,'Discovery 03','O/S behind rear wheel TD5.',null,24);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (101,'Discovery 05','O/S Chassis rail under driver door.',null,24);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (102,'Defender','O/S Chassis rail under driver door.',null,24);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (103,'Defender 05','Front of o/s front wheel.',null,24);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (104,'Freelander','Vertical on bulkhead. 07 Model Bace of rear seat in Boot in front of spare wheel under fome.',null,24);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (105,'Range Rover','03 models O/S suspension mounting. 06 Model O/S Chassis Midway under driver door (near front wheel).',null,24);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (106,'2012 Range Rover','In boot behind rear seats',null,24);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (107,'All models','Bulkhead.',null,25);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (108,'Grand Cou','O/S drivers floor. Under O/S matt driver footwell (remove screws)',null,26);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (109,'M G','O/S Suspension Mountain under cover. Bonnet pull in the boot',null,27);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (110,'121','Floor at drivers seat.',null,28);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (111,'Premacy','Under drivers seat.',null,28);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (112,'3','Bulkhead or under seat.',null,28);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (113,'98 SL320','Panel in front of B/M cylinder.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (114,'190D 87type','Panel in front of B/M cylinder',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (115,'A class','Vertical on bulkhead.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (116,'C class','Under drivers seat.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (117,'S class','Under drivers seat, remove courtesy light on o/s/r & is stamped above fusebox.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (118,'S 320','06 Behind Armrest rear seat.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (119,'Caddy','Rear door pillar.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (120,'SLK','Under plastic panel behind drivers seat.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (121,'S class (new shape)','Pull down centre rear armrest & is stamped on body',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (122,'E class','Under drivers seat.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (123,'CL 600','02 Rear foot well behind fuse box.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (124,'CLK','Under drivers seat.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (125,'SLK','Vertical on bulkhead OR on side of gearbox tunnel beside drivers seat.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (126,'M class','O/S/F footwell facing away.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (127,'Vaneo','Under plastic at Wiper Panel.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (128,'Vito','Drivers floor area.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (129,'X3','Over O/S Suspension Mounting.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (130,'ML 430','00 on chassis under drivers door.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (131,'ML 280','Under rear seat or front cross member.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (132,'SL 500','Behind trim panel under drivers side rear seat at footwell.',null,29);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (133,'Colt Diamond','Under driver seat.',null,30);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (134,'All older car models','Vertical on bulkhead.',null,30);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (135,'Pajero','O/S/R chassis behind wheel.',null,30);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (136,'Delica','On bulkhead.',null,30);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (137,'Micra & Almera','Vertical on bulkhead.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (138,'Primera','Vertical on bulkhead.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (139,'Patrol','O/S Centre way on chassis rail low down.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (140,'Pathfinder 06','O/S Centre way on chassis rail low down.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (141,'Primera (new shape)','Under drivers seat.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (142,'Micra (new shape)','Behind flap on O/S whiper panel.',nullnullSystem.Byte[],31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (143,'Terrano','Midway on o/s chassis.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (144,'Tino','Under drivers seat.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (145,'X Trail','Under drivers seat.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (146,'08 X Trail','Under Cover over B/Fluid',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (147,'Qashqai','07 Under flap o/s wiper',nullnullSystem.Byte[],31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (148,'Pathfinder','On n/s chassis rail under d/door',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (149,'Note','O/S Bulkhead under flap.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (150,'Tida ''07','Under grill in front of o/s wiper spindel.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (151,'Qashquai + 2','Under flap on o/s wiper panel.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (152,'Leaf','Under plastic trim at wiper panel',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (153,'Serena 08','Under small plastic trim on osf door sill',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (154,'Primastar','Under plastic panel under drivers seat.',null,31);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (155,'Corsa','Floor at drivers seat.',null,32);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (156,'Astra & Vectra','Between drivers seat & door sill',null,32);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (157,'Frontera','O/S/R chassis in front of wheel',null,32);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (158,'Insignia 09','Bulk Head.',null,32);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (159,'Agila 2010 on','On lip coming from drivers side bulkhead',null,32);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (160,'Vivaro','Under panel under drivers seat.',null,32);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (161,'106,206,806, Expert','O/S/F valance.',nullnullSystem.Byte[],33);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (162,'107','Under drivers seat.',null,33);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (163,'1007','On lip under o/s wiper spindel.',null,33);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (164,'406, 607','Vertical on bulkhead.',null,33);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (165,'207 GT 07 model','Bulkhead. On lip under n/s wiper spendal.',nullnullSystem.Byte[],33);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (166,'307','Top of o/s shock',nullnullSystem.Byte[],33);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (167,'308','Top of o/s shock mounting.',null,33);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (168,'407','O/S valence facing out.',null,33);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (169,'807','Under wiper blade in middle bottom of screen.',null,33);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (170,'Boxer','Floor at drivers seat.',null,33);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (171,'Expert','O/S valence.',null,33);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (172,'911','O/S Bulkhead.',null,34);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (173,'Cayenne','Boot floor in front of tool kit.',null,34);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (174,'Some models','In front of spare wheel.',null,34);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (175,'Clio 1999','Under drivers seat.',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (176,'Clio 2007','In boot on o/s (Same for estate).',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (177,'Clio, Laguna, RX4','Front valance.',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (178,'Espace','Centre of drip rail under wipers',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (179,'Scenic R4','boot floor.',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (180,'Scenic 04','In front of engine mounting o/s.',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (181,'Scenic','Boot floor under spare wheel.',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (182,'Laguna (new shape)','08 on lip under n/s wiper spindal',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (183,'Laguna (old shape)','Under flap at wiper panel.',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (184,'Modus','Note boot',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (185,'Megane 03','In front of engine mounting o/s.',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (186,'Megane ''08','Drivers door pillor over check strap.',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (187,'Traffic','Floor near drivers seat.',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (188,'Kangoo 04','Under drivers seat.',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (189,'Fluence ''09','Behind drivers seat.',null,35);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (190,'25 & 45','Vertical on bulkhead.',null,36);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (191,'75','Suspension mounting area',null,36);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (192,'Mini','On drip rail under bonnet',null,36);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (193,'Mini (new shape)','Suspension mounting area',null,36);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (194,'93','Vertical on bulkhead under vent',null,37);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (195,'95','Vertical on bulkhead & in boot.',null,37);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (196,'Arosa, Toledo','Horizontal on wiper panel',null,38);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (197,'Ibiza','Vertical on bulkhead or top of o/s shock near the valance',null,38);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (198,'Alhambra','Horizontal on wiper panel',null,38);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (199,'2 Door Model','Stamped on rear body behind engine cover',null,39);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (200,'For Four','05 Under drivers seat. Next to battery (Lift up carpet OS footwell) left hand drive',null,39);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (201,'Kyron','Behind o/s front wheel under rubber flap',null,40);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (202,'Felicia.','Top of O/S suspension mounting.',null,41);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (203,'Fabia','O/S/F suspension mounting area.',null,41);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (204,'Octavia & Superb','On bullkhead.',nullnullSystem.Byte[],41);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (205,'Octavia 05','Top of O/S suspension mounting.',null,41);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (206,'Roomster.','Top of O/S suspension mounting.',null,41);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (207,'Yeti','Top of O/S suspension mounting.',null,41);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (208,'Grandvitara','Behind o/s front wheel',null,42);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (209,'Jimny','In front of o/s rear wheel',null,42);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (210,'Wagon R','Bulkhead.',null,42);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (211,'Swift 07','O/S Bonnet Hindge',null,42);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (212,'2012 Vitara','On bulkhead.',null,42);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (213,'Legacy','Behind brake M/cylinder',null,43);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (214,'Impreza','Behind brake M/cylinder',null,43);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (215,'Yaris','Under flap on bulkhead.',null,44);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (216,'Yaris(EPS)','On panel under drivers seat',null,44);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (217,'Corolla, Carina','On bulkhead',null,44);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (218,'Corolla, Avensis','On panel under drivers seat',null,44);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (219,'Celica, Picnic','On panel under drivers seat',null,44);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (220,'Hiace','On step at drivers door',null,44);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (221,'Prius','O/S bulkhead',null,44);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (222,'Verso','Midway on bulk head',null,44);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (223,'Landcruiser','O/S/F or O/S/R chassis behind wheel.',null,44);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (224,'RAV 4 01','Under drivers seat',null,44);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (225,'Auris','Under drivers seat.',null,44);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (226,'Caddy Maxi','08 Behind R/H tail lamp (remove jack)',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (227,'Beetle','Under rear seat.',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (228,'Golf','Under bonnet rubber on wing. ',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (229,'Golf Plus 05','Top of shock o/s',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (230,'Golf Plus 07','Along side o/s bonnet hinge through hole in plastic',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (231,'Lupo, Golf, Passat','Vertical on bulkhead.',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (232,'Toureg','Under false floor & carpet at o/s/r passenger footwell. 05 Modelin boot also ''07 Model in front of spare wheel o/s.',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (233,'Caravelle','O/S/F wiper spindle area',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (234,'Polo','O/S Conor of suspension top and valance may be covered in wax,',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (235,'Polo Fox','Under rear seat.',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (236,'Vaneo','Centre of Bulkhead.',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (237,'Vivto','Tool box O/S. Remove plastic box on o/s number on pillar.',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (238,'Touran','Under rear seat. 05 O/S rear foot well.',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (239,'Tiguan','O/S front top of shock.',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (240,'Up ''12','O/S front valance near shock',null,45);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (241,'S40 & S60','Vertical on bulkhead.',null,46);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (242,'2012 S60','Under drivers seat.',null,46);
insert into `viconnect`.`model`(`ModelID`,`ModelName`,`Description`,`Image`,`MakeID`) values (243,'2012 V60','Under drivers seat.',null,46);
